spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:mariadb://localhost/rainbow-academic-management
    username: root
    password: green502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.rainbowuniv.academicmenagmentbe.dto