constants:
  file:
    directory: D:\student\jyj\backend\upload

spring:
  application:
    name: rainbow-academic-management
  datasource:

    url: jdbc:log4jdbc:mariadb://192.168.0.39/rainbow-academic-management
    username: green3
    password: figma502

    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
