constants:
  file:
    directory: /home/download

spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.39/first_project
    username: green3
    password: figma502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mail:
  smtp:
    host: "smtp.gmail.com"
    username: "mujiuniv@gmail.com"
    password: "dqknokdqkusfndls"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml