spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:mariadb://192.168.0.39/rainbow-academic-management
    username: green3
    password: figma502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml