constants:
  file:
    directory: /home/download

spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/lms
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
