spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/musiuniver
    username: root
    password: green502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml