constants:
  file:
    directory: /home/download

spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:mariadb://127.0.0.1/musiuniver
    username: root
    password: green502
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml