constants:
  file:
    directory: /home/download/

spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:mariadb://localhost/musiuniver
    username: root
    password: green502
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
