constants:
  file:
    directory: D:\student\jyj\backend\upload

spring:
  application:
    name: rainbow-academic-management
  datasource:
    url: jdbc:mariadb://192.168.0.39/first_project
    username: green3
    password: figma502
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/**/*.xml
type-aliases-package: com.rainbowuniv.academicmenagmentbe.Attendance.model